[2024-03-24 00:32:53] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:31:53+00:00
[2024-03-24 00:35:30] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:39:47+00:00
[2024-03-24 00:38:29] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:42:46+00:00
[2024-03-24 00:38:29] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:38:33] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:42:50+00:00
[2024-03-24 00:38:33] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:38:33] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:42:51+00:00
[2024-03-24 00:38:33] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:38:34] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:42:52+00:00
[2024-03-24 00:38:34] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:38:35] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:42:52+00:00
[2024-03-24 00:38:35] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:42:09] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:46:26+00:00
[2024-03-24 00:42:09] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:42:09] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:46:27+00:00
[2024-03-24 00:42:10] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:42:10] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - @Andtheking ha eseguito /start alle 2024-03-23 23:46:27+00:00
[2024-03-24 00:42:10] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Andtheking, 245996916 - Ha eseguito /start
[2024-03-24 00:43:34] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(edited_message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 23, 23, 47, 47, tzinfo=<UTC>), delete_chat_photo=False, edit_date=datetime.datetime(2024, 3, 23, 23, 47, 51, tzinfo=<UTC>), from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5256, supergroup_chat_created=False, text='.impostaClasse'), update_id=706151857)" caused error "'NoneType' object has no attribute 'text'"
[2024-03-24 00:55:15] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 23, 23, 59, 32, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5268, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151871)" caused error "Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied."
[2024-03-24 00:55:41] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 23, 23, 59, 58, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5269, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151872)" caused error "object NoneType can't be used in 'await' expression"
[2024-03-24 00:57:01] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 0, 24, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5270, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151873)" caused error "object list can't be used in 'await' expression"
[2024-03-24 00:57:46] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 1, 51, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5271, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151874)" caused error "object list can't be used in 'await' expression"
[2024-03-24 00:59:43] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 1, 51, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5271, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151874)" caused error "parameters are of unsupported type"
[2024-03-24 01:00:06] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 4, 20, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5272, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151875)" caused error "parameters are of unsupported type"
[2024-03-24 01:00:26] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 4, 43, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5273, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151876)" caused error "'>' not supported between instances of 'tuple' and 'int'"
[2024-03-24 01:20:02] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Inserito nel DB il seguente utente: 245996916,@Andtheking
[2024-03-24 01:24:55] - D:\Cartella\Puttanaio 2.0\Develop\Roba con Python\Bot telegram\Bot seri\Prof assenti\bot.py - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Andtheking', id=245996916, type=<ChatType.PRIVATE>, username='Andtheking'), date=datetime.datetime(2024, 3, 24, 0, 29, 13, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Andtheking', id=245996916, is_bot=False, language_code='it', username='Andtheking'), group_chat_created=False, message_id=5295, supergroup_chat_created=False, text='.impostaClasse 5I'), update_id=706151889)" caused error "Error binding parameter 0 - probably unsupported type."
